sources:
    - webscan
    - rapiddns
    - ip138
    - yougetsignal
    - aizhan
    - chinaz
    - viewdns
    - c99
    - bugscaner
    - hackertarget
    - dnslytics
    - omnisint
    - dnsgrep
    - domaintools
    - securitytrails
    - fofa
    - shodan
all-sources:
    - webscan
    - rapiddns
    - ip138
    - yougetsignal
    - aizhan
    - c99
    - chinaz
    - viewdns
    - bugscaner
    - hackertarget
    - dnslytics
    - omnisint
    - dnsgrep
    - domaintools
    - securitytrails
    - fofa
    - shodan
proxy: "http://127.0.0.1:8080/"
dnsgrep: []
c99:
    - XXXXX-XXXXX-XXXXX-XXXXX
shodan:
    - XXXXX-XXXXX-XXXXX-XXXXX
fofa:
    - XXXXX@gmail.com:xxx
iplookup-version: "1.1"
